- name: install mysql server and python module
  yum: name={{ item }} state=present
  with_items:
    - mysql-server
    - MySQL-python

- name: enable mysql
  service: name=mysqld enabled=yes

- name: start mysql
  service: name=mysqld state=started

- name: drop test database
  mysql_db: name=test
            state=absent
            login_user=root
            login_password=

- name: drop anonymous user
  mysql_user: name=
              host={{ item }}
              state=absent
              login_user=root 
              login_password=
  with_items:
    - localhost
    - "{{ ansible_hostname }}"

- name: change root password
  mysql_user: login_user=root
              login_password=
              name=root 
              host={{ item }}
              password={{ mysql_password }}
  with_items:
    - 127.0.0.1
    - "{{ ansible_hostname }}"
    - localhost
