- name: Install apache
  yum: name=httpd state=present

- name: Enable apache
  service: name=httpd enabled=yes

- name: start apache
  service: name=httpd state=started

- name: Enable port 80
  lineinfile: dest=/etc/sysconfig/iptables
              regexp="80 -j ACCEPT$"
              line="-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT"
              insertafter="-A INPUT -i lo -j ACCEPT"
  notify: restart-iptables

- name: setup apache as reverse proxy
  lineinfile: dest=/etc/httpd/conf/httpd.conf
              line="{{ item }}"
              insertafter=EOF
  with_items:
    - "ProxyPass        / http://localhost:7990/ connectiontimeout=5 timeout=300"
    - "ProxyPassReverse / http://localhost:7990/"
  notify: restart-apache
